[package]
name = "external-buffered-stream"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1" }
futures = "0.3.31"
log = "0.4.27"
sled = { version = "0.34" }

[dev-dependencies]
tempfile = "3.0"
tokio = { version = "1.0", features = ["full"] }
env_logger = "0.11"

